version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 100
    insecure-external-code-execution: allow
    registries: "*"
